# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ContactUsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Video',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Home Page Video',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('major', models.CharField(choices=[('Accounting', 'Accounting'), ('Economics', 'Economics'), ('Finance', 'Finance'), ('Management', 'Management'), ('Management Information System', 'Management Information System'), ('Marketing', 'Marketing'), ('Operation & Supply Chain Managment', 'Operation & Supply Chain Managment'), ('Public Administration', 'Public Administration')], max_length=64, verbose_name='Major')),
                ('skills', models.TextField(verbose_name='Skills')),
                ('interests', models.TextField(verbose_name='Interests')),
                ('position', models.CharField(max_length=64, verbose_name='Position')),
                ('rank', models.IntegerField(verbose_name='Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_picture', to='club.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('video_id', models.CharField(max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_video', to='club.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomingWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcoming_word', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Welcoming Word',
            },
        ),
    ]
