# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('All Other CBA Courses', 'All Other CBA Courses'), ('MIS Curriculum Guide', 'MIS Curriculum Guide'), ('OSCM Curriculum Guide', 'OSCM Curriculum Guide'), ('Student Placement', 'Student Placement')], max_length=64, null=True, unique=True, verbose_name='Name')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='department.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=128)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('twitter_account', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, choices=[('', ''), ('Dr.', 'Dr.'), ('Eng.', 'Eng.'), ('Prof.', 'Prof.'), ('TA.', 'TA.')], default='', max_length=64, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('semester', models.CharField(default='Spring 2016/2017', max_length=128)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='department.FacultyMember')),
            ],
        ),
    ]
